name: Build and Test

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  build-linux-run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: show Ubuntu version
      run: cat /etc/os-release | grep PRETTY_NAME | awk -F '=' '{print $2}'
    - name: update build environment
      run: sudo apt-get update --fix-missing -y && sudo apt-get upgrade --fix-missing -y
    - name: install prerequisites
      run: |
       sudo apt-get install -y avahi-daemon libavahi-client-dev libssl-dev libpam-dev libusb-1.0-0-dev zlib1g-dev
       sudo apt install autotools-dev autopoint cmake libtool pkg-config libcups2-dev libexif-dev liblcms2-dev libfontconfig1-dev
       sudo apt install libfreetype6-dev build-essential qtbase5-dev qtchooser libcairo2-dev libboost-system-dev libboost-thread-dev libboost-program-options-dev libboost-test-dev libopenjp2-7-dev liblcms2-dev libjpeg-dev
       sudo apt install -y libjxl-dev
    - name: Install pdfio >= 1.6.0
      run: |
        cd ..
        mkdir pdfio
        wget https://github.com/michaelrsweet/pdfio/releases/download/v1.6.0/pdfio-1.6.0.tar.gz
        tar -xzf pdfio-1.6.0.tar.gz
        cd pdfio-1.6.0
        ./configure --prefix=/usr --enable-shared
        make all
        make test
        sudo make install
        cd ..
        cd ..
    - name: Install poppler and mupdf
      run: |
       sudo apt install libpoppler-cpp-dev libpython3-dev libdbus-1-dev
       sudo apt install mupdf-tools
       sudo apt install -y poppler-utils
       
    - name: Install ghostscript
      run: sudo apt install ghostscript

    - name: configure 
      env:
        CC: /usr/bin/gcc
      run: ./autogen.sh && ./configure --enable-debug
    - name: make
      run: make
    - name: Run Tests
      run: make check || cat test/error_log*
